remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme #
title: Focal-plane wavefront control using deep learning for high-contrast imaging
description: Additional documents and further explanations
